# -*- coding: utf-8 -*-
"""Assignment1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BmfsL48ANSJgMLvD95ecic80O9N-OYRu
"""

# Install the package for bar chart racing
!pip install bar-chart-race

#Import Libraries

import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
import plotly.express as px
import plotly.graph_objects as go
import seaborn as sns
import bar_chart_race as bcr


# Ignore any further warnings

import warnings
warnings.filterwarnings('ignore')

""">  # **TASK 1: Analytical Question**




With the Kaggle dataset on causes of deaths worldwide numerous analytical queries on mortality rates in various nations can be invetigated. or this study, the guiding analytical question investigated using this dataset is:



- What are the leading causes of death in different in the world with specific focus on Nigeria?


Given the growing concern around the world over rising mortality rates and the requirement to identify efficient public health interventions to address the main causes of death, this analytical question is especially pertinent, this analytical question aims to investigate the global variance in the top causes of death before presenting a detailed empirical examination of Nigeria's top causes of mortality. Researchers can learn more about the variables influencing mortality rates and the leading causes of death by analysing the statistics.

# **TASK 2 (Data analysis**)
"""

#data pre-processing
#Read Dataset

df = pd.read_csv('/content/cause_of_deaths.csv')
df.head(10)

#check the data frame
df.shape

#Check for data type

df.dtypes

#Check for missing data

df.isnull().sum()

#Check for duplicate data

df.duplicated().sum()

#Rename column

df=df.rename(columns={'Country/Territory':'Country'})

df.head()

#check the number of countries included in the analysis
print(f'There are  {len(df["Country"].unique())}  countries')

#Check for number of unique records present in the data

df.nunique(axis=0)

#intial overview of the Statistical Information 

df.describe()

"""**Exploratory Data Analysis (EDA)**"""

#Create a new column for the total number of deaths (Sum all cause of deaths)

cause_of_deaths = [col for col in df.columns if col not in ('Country', 'Code', 'Year')]

df['Total_deaths'] = df[cause_of_deaths].sum(axis=1)

df.head()

#Find the total number of each disease and rename columns for the chart

disease_df = df[cause_of_deaths].sum().to_frame().reset_index()
disease_df.rename(columns={"index": "Disease", 0:"Total cases"}, inplace=True)
disease_df

#create percentage cause of Deaths
fig = px.sunburst(disease_df, 
                  path=['Disease'], 
                  values='Total cases'
                  )

fig.update_traces(textinfo='label+percent parent')    
fig.update_layout(title_text='Percentage of Cause of Deaths', title_x=0.5, font_size=15)
fig.show()

"""The analysis showed that cardiovascular diseases are the largest cause of death worldwide, accounting for 30% of all mortality. The World Health Organisation (WHO) report on the world's main causes of death, which names cardiovascular illnesses as the leading cause of mortality (WHO, 2020), is consistent with this conclusion. The statistics also showed that among the leading causes of mortality globally were neoplasms (16%), chronic respiratory disorders (7%), and lower respiratory diseases (6%). Additionally, 5% of the deaths worldwide were caused by neonatal disorders.

These results have important ramifications for international public health, underscoring the need of focused measures to stop and treat these major causes of mortality. For instance, efforts to lower the incidence and prevalence of cardiovascular diseases could include lifestyle changes like increased physical activity, a healthy diet, and programmes to help people quit smoking, as well as better access to efficient medical interventions like hypertension and cholesterol-lowering drugs (Yusuf et al., 2021). Similar efforts might be made to prevent and manage chronic and lower respiratory illnesses using a variety of interventions, such as immunisation campaigns, steps to reduce air pollution, and early detection and treatment techniques (WHO, 2017).
"""

df.head()



"""After determining the percentage cause of death worldwide, this study moved on to examine the exact leading causes of mortality in Nigeria. The researcher's own nation of Nigeria and the growing discussion about the numerous public health concerns that are driving up mortality rates there were two factors that motivated the choice of Nigeria. Nigeria is one of the nations with one of the largest burdens of infectious illnesses, including HIV/AIDS, TB, and malaria (WHO, 2021). Non-communicable diseases (NCDs), such as diabetes, cancer, and cardiovascular disease, are also becoming more prevalent and are raising death rates in the nation. Hence this study would analyze the current data to present empirical findings on the actual top casuses of death in the country


"""

#Create a new data frame of Nigeria

Nigeria=df[df['Country']=='Nigeria']
Nigeria.head()

"""# ESTIMATION OF THE MORTALITY TREND IN NIGERIA 

"""

#Find the total number of each disease and rename columns for the chart

NG_disease = Nigeria[cause_of_deaths].sum().to_frame().reset_index()
NG_disease.rename(columns={"index": "Disease", 0:"Total cases"}, inplace=True)
NG_disease

"""# **Time Series of Total Number of Deaths**"""

NG_Deaths_by_year = Nigeria.groupby('Year')['Total_deaths'].sum().reset_index()

NG_Deaths_by_year

plt.figure(figsize=(16,9))

sns.lineplot(data = NG_Deaths_by_year,
             x='Year',
             y = 'Total_deaths'
            )

plt.xlabel('Year',fontsize =12)
plt.ylabel('Total Number of Deaths',fontsize =12)
plt.title('Time Series of Total Number of Deaths in Nigeria', fontsize=15)

plt.show()

"""**Percentage of Cause of Deaths in Nigeria**"""

# Visualisation by Treemap

fig = px.treemap(NG_disease, 
                 path = [px.Constant('Total cases'), 'Disease'], 
                 values = 'Total cases'
                 )

fig.update_traces(textinfo='label+percent parent')    
fig.update_layout(title_text='Percentage of Cause of Deaths in Nigeria', title_x=0.5, font_size=15)
fig.show()

"""upon narrowing the scope of the study to Nigeria, it was discovered that diarrheal diseases (17%), malaria (15%), lower respiratory infections (14%), neonatal disorders (12%), and cardiovascular diseases (10%) were the main contributors to the percentage of cause of deaths in the country."""

#Top 5 Cause of Deaths in Nigeria
NG_top5_disease = NG_disease.groupby('Disease')['Total cases'].sum().sort_values(ascending=False).head(5).reset_index()
NG_top5_disease

fig = go.Figure(data=[go.Pie(labels=NG_top5_disease['Disease'],
                             values=NG_top5_disease['Total cases'],
                             hole=.7,
                             title = 'Top 5 Cause of deaths')])

fig.update_layout(title='Top 5 Cause of Deaths in Nigeria',title_x=0.5, font_size=15, showlegend = False)
fig.update_traces(textposition='outside', textinfo='percent+label')
fig.show()

#Create Time series of 5 cause of deaths - Diarrheal Diseases, Malaria, Lower Respiratory Infections, Neonatal Disorders, Cardiovascular Diseases

fig = go.Figure()
fig.add_trace(go.Scatter(x = Nigeria['Year'],
                         y = Nigeria['Diarrheal Diseases'],
                         mode = 'lines',
                         name = 'Diarrheal Diseases',
                         marker_color = 'Red',
                         line = dict(dash = 'dashdot')))

fig.add_trace(go.Scatter(x = Nigeria['Year'],
                         y = Nigeria['Malaria'],
                         mode = 'lines',
                         name = 'Malaria',
                         marker_color = 'DarkOrchid',
                         line = dict(dash = 'dot')))

fig.add_trace(go.Scatter(x = Nigeria['Year'],
                         y = Nigeria['Lower Respiratory Infections'],
                         mode = 'lines',
                         name = 'Lower Respiratory Infections',
                         marker_color = 'RoyalBlue'
                         ))

fig.add_trace(go.Scatter(x = Nigeria['Year'],
                         y = Nigeria["Neonatal Disorders"],
                         mode = 'lines',
                         name = "Neonatal Disorders",
                         marker_color = 'Black',
                         line = dict(dash = 'dot')))
                                         

fig.add_trace(go.Scatter(x = Nigeria['Year'],
                         y = Nigeria['Cardiovascular Diseases'],
                         mode = 'lines',
                         name = 'Cardiovascular Diseases',
                         marker_color = 'LightSeaGreen',
                         line = dict(dash = 'dash')))
                         
fig.update_layout(title = '<b>Time Series of Top 5 Cause of Deaths in New Zealand<b>',
                  title_x = 0.5,
                  title_font= dict(size = 20),
                  xaxis_title = 'Year',
                  yaxis_title = 'Total Number of Deaths',
                  template = 'plotly_white')

fig.show()